services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - default-net
    env_file:
    - .env

  frontend:
      build: ./react-frontend
      container_name: react_frontend
      ports:
        - "5173:5173" 
      depends_on:
        - backend
      networks:
        - default-net
      environment:
        - CHOKIDAR_USEPOLLING=true
      env_file:
        - .env

networks:
  default-net:
    driver: bridge
